// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Acceptance.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class InvoiceLifecycleFeature : object, Xunit.IClassFixture<InvoiceLifecycleFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "InvoiceLifecycle.feature"
#line hidden
        
        public InvoiceLifecycleFeature(InvoiceLifecycleFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Invoice Lifecycle", "  As a Building Owner\r\n  I want to send, collect payment for, and void invoices\r\n" +
                    "  So that billing follows the rental and financial-reporting rules", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 10
  #line hidden
#line 11
    await testRunner.GivenAsync("the owner has a building with room \"101\" renting at 5000000 VND and an active ten" +
                    "ant contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner sends a Draft invoice to the tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Owner sends a Draft invoice to the tenant")]
        [Xunit.TraitAttribute("Category", "Send")]
        public async System.Threading.Tasks.Task OwnerSendsADraftInvoiceToTheTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "Send"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Owner sends a Draft invoice to the tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("an invoice in \"Draft\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("the owner sends the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("the invoice status should be \"Sent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot send an invoice that is not in Draft status")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Cannot send an invoice that is not in Draft status")]
        [Xunit.TraitAttribute("Category", "Send")]
        public async System.Threading.Tasks.Task CannotSendAnInvoiceThatIsNotInDraftStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "Send"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot send an invoice that is not in Draft status", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync("the owner sends the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("the operation should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
    await testRunner.AndAsync("the invoice status should be \"Sent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Partial payment moves a Sent invoice to PartiallyPaid")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Partial payment moves a Sent invoice to PartiallyPaid")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task PartialPaymentMovesASentInvoiceToPartiallyPaid()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Partial payment moves a Sent invoice to PartiallyPaid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 36
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 37
    await testRunner.WhenAsync("the owner records a payment of 2000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("the invoice status should be \"PartiallyPaid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
    await testRunner.AndAsync("a payment of 2000000 VND should be recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full payment marks the invoice as Paid")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Full payment marks the invoice as Paid")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task FullPaymentMarksTheInvoiceAsPaid()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Full payment marks the invoice as Paid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 43
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
    await testRunner.WhenAsync("the owner records a payment of 5000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the invoice status should be \"Paid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Payment is blocked on a Draft invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Payment is blocked on a Draft invoice")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task PaymentIsBlockedOnADraftInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Payment is blocked on a Draft invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.GivenAsync("an invoice in \"Draft\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.WhenAsync("the owner records a payment of 5000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 51
    await testRunner.ThenAsync("the operation should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
    await testRunner.AndAsync("no payment should be recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Payment is blocked on a Void invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Payment is blocked on a Void invoice")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task PaymentIsBlockedOnAVoidInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Payment is blocked on a Void invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 56
    await testRunner.GivenAsync("an invoice in \"Void\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
    await testRunner.WhenAsync("the owner records a payment of 5000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the operation should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("no payment should be recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Overpayment beyond the invoice total is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Overpayment beyond the invoice total is rejected")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task OverpaymentBeyondTheInvoiceTotalIsRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Overpayment beyond the invoice total is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("the owner records a payment of 6000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("the operation should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.AndAsync("no payment should be recorded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner voids a Sent invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Owner voids a Sent invoice")]
        [Xunit.TraitAttribute("Category", "Void")]
        public async System.Threading.Tasks.Task OwnerVoidsASentInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Void"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Owner voids a Sent invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 74
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 75
    await testRunner.WhenAsync("the owner voids the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.ThenAsync("the invoice status should be \"Void\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot void a fully Paid invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Cannot void a fully Paid invoice")]
        [Xunit.TraitAttribute("Category", "Void")]
        public async System.Threading.Tasks.Task CannotVoidAFullyPaidInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Void"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot void a fully Paid invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync("an invoice in \"Paid\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.WhenAsync("the owner voids the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 82
    await testRunner.ThenAsync("the operation should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
    await testRunner.AndAsync("the invoice status should be \"Paid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot void an already voided invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Cannot void an already voided invoice")]
        [Xunit.TraitAttribute("Category", "Void")]
        public async System.Threading.Tasks.Task CannotVoidAnAlreadyVoidedInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Void"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot void an already voided invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 87
    await testRunner.GivenAsync("an invoice in \"Void\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 88
    await testRunner.WhenAsync("the owner voids the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 89
    await testRunner.ThenAsync("the operation should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Staff cannot void an invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Staff cannot void an invoice")]
        [Xunit.TraitAttribute("Category", "Void")]
        [Xunit.TraitAttribute("Category", "Authorization")]
        public async System.Threading.Tasks.Task StaffCannotVoidAnInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Void",
                    "Authorization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Staff cannot void an invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 92
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 93
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 94
    await testRunner.WhenAsync("a staff member voids the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("the operation should be rejected with a permission error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
    await testRunner.AndAsync("the invoice status should be \"Sent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tenant cannot void an invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Invoice Lifecycle")]
        [Xunit.TraitAttribute("Description", "Tenant cannot void an invoice")]
        [Xunit.TraitAttribute("Category", "Void")]
        [Xunit.TraitAttribute("Category", "Authorization")]
        public async System.Threading.Tasks.Task TenantCannotVoidAnInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Void",
                    "Authorization"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tenant cannot void an invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 99
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 100
    await testRunner.GivenAsync("an invoice in \"Sent\" status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 101
    await testRunner.WhenAsync("the tenant voids the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 102
    await testRunner.ThenAsync("the operation should be rejected with a permission error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
    await testRunner.AndAsync("the invoice status should be \"Sent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await InvoiceLifecycleFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await InvoiceLifecycleFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
