// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Acceptance.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MonthlyInvoiceCalculationFeature : object, Xunit.IClassFixture<MonthlyInvoiceCalculationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "InvoiceCalculation.feature"
#line hidden
        
        public MonthlyInvoiceCalculationFeature(MonthlyInvoiceCalculationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Monthly Invoice Calculation", "  As a Building Owner\r\n  I want invoices calculated correctly\r\n  So I get paid fa" +
                    "irly and tenants can verify billing", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a building owner with email \"owner@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("a building named \"Test Building\" owned by the owner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("a room \"101\" in the building with rent 5000000 VND per month", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("a tenant with email \"tenant@test.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("an active contract between tenant and room \"101\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("room \"101\" has 1 occupant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate full monthly rent")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate full monthly rent")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task CalculateFullMonthlyRent()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate full monthly rent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.GivenAsync("the contract is active for the entire month of March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table1.AddRow(new string[] {
                            "ActiveDays",
                            "31"});
                table1.AddRow(new string[] {
                            "RoomAmount",
                            "5000000"});
                table1.AddRow(new string[] {
                            "TotalAmount",
                            "5000000"});
#line 23
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table1, "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("invoice status should be \"Draft\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate prorated rent for first month")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate prorated rent for first month")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task CalculateProratedRentForFirstMonth()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate prorated rent for first month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("the contract starts on \"2026-03-16\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table2.AddRow(new string[] {
                            "ActiveDays",
                            "16"});
                table2.AddRow(new string[] {
                            "RoomAmount",
                            "2580645"});
#line 37
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate prorated rent for last month")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate prorated rent for last month")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task CalculateProratedRentForLastMonth()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate prorated rent for last month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("the contract ends on \"2026-03-10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 47
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table3.AddRow(new string[] {
                            "ActiveDays",
                            "10"});
                table3.AddRow(new string[] {
                            "RoomAmount",
                            "1612903"});
#line 48
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table3, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full rent applied when contract spans multiple months")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Full rent applied when contract spans multiple months")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task FullRentAppliedWhenContractSpansMultipleMonths()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Full rent applied when contract spans multiple months", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 56
      await testRunner.GivenAsync("the contract starts on \"2026-02-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
      await testRunner.AndAsync("the contract ends on \"2026-04-20\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
      await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table4.AddRow(new string[] {
                            "ActiveDays",
                            "31"});
                table4.AddRow(new string[] {
                            "RoomAmount",
                            "5000000"});
#line 59
      await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table4, "Then ");
#line hidden
#line 63
      await testRunner.AndAsync("rent should not be prorated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Ensure no off-by-one error for full month calculation")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Ensure no off-by-one error for full month calculation")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task EnsureNoOff_By_OneErrorForFullMonthCalculation()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ensure no off-by-one error for full month calculation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 67
      await testRunner.GivenAsync("the contract is active from \"2026-03-01\" to \"2026-03-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 68
      await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table5.AddRow(new string[] {
                            "ActiveDays",
                            "31"});
                table5.AddRow(new string[] {
                            "RoomAmount",
                            "5000000"});
#line 69
      await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table5, "Then ");
#line hidden
#line 73
      await testRunner.AndAsync("rent should not be prorated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate prorated rent when contract starts and ends in same month")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate prorated rent when contract starts and ends in same month")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task CalculateProratedRentWhenContractStartsAndEndsInSameMonth()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate prorated rent when contract starts and ends in same month", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 76
    await testRunner.GivenAsync("the contract starts on \"2026-03-10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 77
    await testRunner.AndAsync("the contract ends on \"2026-03-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "ActiveDays",
                            "6"});
                table6.AddRow(new string[] {
                            "RoomAmount",
                            "967742"});
#line 79
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Return validation error when active days are invalid")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Return validation error when active days are invalid")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task ReturnValidationErrorWhenActiveDaysAreInvalid()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Return validation error when active days are invalid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 88
    await testRunner.GivenAsync("active days is -1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("validation error should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
    await testRunner.AndAsync("no invoice should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Return validation error when monthly rent is missing")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Return validation error when monthly rent is missing")]
        [Xunit.TraitAttribute("Category", "Rent")]
        public async System.Threading.Tasks.Task ReturnValidationErrorWhenMonthlyRentIsMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "Rent"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Return validation error when monthly rent is missing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 96
    await testRunner.GivenAsync("room \"101\" has no monthly rent configured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 97
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 98
    await testRunner.ThenAsync("validation error should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 99
    await testRunner.AndAsync("no invoice should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate service amount using occupant count")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate service amount using occupant count")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task CalculateServiceAmountUsingOccupantCount()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate service amount using occupant count", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 108
    await testRunner.GivenAsync("internet service enabled with unit price 100000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 109
    await testRunner.AndAsync("service quantity is based on occupant count", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 110
    await testRunner.AndAsync("room \"101\" has 3 occupants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 111
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "ServiceQuantity",
                            "3"});
                table7.AddRow(new string[] {
                            "ServiceAmount",
                            "300000"});
                table7.AddRow(new string[] {
                            "TotalAmount",
                            "5300000"});
#line 112
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table7, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate service amount using override quantity")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate service amount using override quantity")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task CalculateServiceAmountUsingOverrideQuantity()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate service amount using override quantity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 122
    await testRunner.GivenAsync("cleaning service enabled with unit price 50000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.AndAsync("override quantity is 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table8.AddRow(new string[] {
                            "ServiceQuantity",
                            "2"});
                table8.AddRow(new string[] {
                            "ServiceAmount",
                            "100000"});
#line 125
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Use default quantity when quantity source does not exist")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Use default quantity when quantity source does not exist")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task UseDefaultQuantityWhenQuantitySourceDoesNotExist()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Use default quantity when quantity source does not exist", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 133
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 134
    await testRunner.GivenAsync("parking service enabled with unit price 200000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 135
    await testRunner.AndAsync("service quantity source does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 136
    await testRunner.AndAsync("override quantity does not exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 137
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table9.AddRow(new string[] {
                            "ServiceQuantity",
                            "1"});
                table9.AddRow(new string[] {
                            "ServiceAmount",
                            "200000"});
#line 138
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table9, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate metered service using override unit price")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate metered service using override unit price")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task CalculateMeteredServiceUsingOverrideUnitPrice()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate metered service using override unit price", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 146
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 147
    await testRunner.GivenAsync("water service enabled with unit price 10000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 148
    await testRunner.AndAsync("override unit price is 15000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Previous",
                            "Current"});
                table10.AddRow(new string[] {
                            "-----------",
                            "----------"});
                table10.AddRow(new string[] {
                            "100",
                            "110"});
#line 149
    await testRunner.AndAsync("meter reading for room \"101\":", ((string)(null)), table10, "And ");
#line hidden
#line 155
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table11.AddRow(new string[] {
                            "Consumption",
                            "10"});
                table11.AddRow(new string[] {
                            "UnitPrice",
                            "15000"});
                table11.AddRow(new string[] {
                            "ServiceAmount",
                            "150000"});
#line 156
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table11, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Create service item with zero consumption")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Create service item with zero consumption")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task CreateServiceItemWithZeroConsumption()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create service item with zero consumption", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 165
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 166
    await testRunner.GivenAsync("electricity service enabled with unit price 3500 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Previous",
                            "Current"});
                table12.AddRow(new string[] {
                            "-----------",
                            "----------"});
                table12.AddRow(new string[] {
                            "1000",
                            "1000"});
#line 167
    await testRunner.AndAsync("meter reading for room \"101\":", ((string)(null)), table12, "And ");
#line hidden
#line 173
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table13.AddRow(new string[] {
                            "Consumption",
                            "0"});
                table13.AddRow(new string[] {
                            "ServiceAmount",
                            "0"});
#line 174
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table13, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Skip service item when room service is disabled")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Skip service item when room service is disabled")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task SkipServiceItemWhenRoomServiceIsDisabled()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Skip service item when room service is disabled", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 182
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 183
    await testRunner.GivenAsync("water service is disabled for room \"101\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 184
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 185
    await testRunner.ThenAsync("no service item should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Show warning when meter reading is missing")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Show warning when meter reading is missing")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task ShowWarningWhenMeterReadingIsMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Show warning when meter reading is missing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 189
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 190
    await testRunner.GivenAsync("electricity service enabled with unit price 3500 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 191
    await testRunner.AndAsync("no meter reading exists for room \"101\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 192
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 193
    await testRunner.ThenAsync("warning \"Meter reading missing\" should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 194
    await testRunner.AndAsync("service item should not be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Override unit price takes priority over default service price")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Override unit price takes priority over default service price")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task OverrideUnitPriceTakesPriorityOverDefaultServicePrice()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Override unit price takes priority over default service price", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 196
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 197
    await testRunner.GivenAsync("water service enabled with unit price 10000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 198
    await testRunner.AndAsync("override unit price is 15000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 199
    await testRunner.AndAsync("room \"101\" has 10 consumption units", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 200
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table14.AddRow(new string[] {
                            "UnitPrice",
                            "15000"});
                table14.AddRow(new string[] {
                            "ServiceAmount",
                            "150000"});
#line 201
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table14, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Override quantity takes priority over occupant count")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Override quantity takes priority over occupant count")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task OverrideQuantityTakesPriorityOverOccupantCount()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Override quantity takes priority over occupant count", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 207
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 208
    await testRunner.GivenAsync("cleaning service enabled with unit price 50000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 209
    await testRunner.AndAsync("room \"101\" has 5 occupants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 210
    await testRunner.AndAsync("override quantity is 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 211
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table15.AddRow(new string[] {
                            "ServiceQuantity",
                            "2"});
                table15.AddRow(new string[] {
                            "ServiceAmount",
                            "100000"});
#line 212
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table15, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Use occupant count when override quantity is missing")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Use occupant count when override quantity is missing")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task UseOccupantCountWhenOverrideQuantityIsMissing()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Use occupant count when override quantity is missing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 218
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 219
    await testRunner.GivenAsync("internet service enabled with unit price 100000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 220
    await testRunner.AndAsync("room \"101\" has 3 occupants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 221
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table16.AddRow(new string[] {
                            "ServiceQuantity",
                            "3"});
#line 222
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table16, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Return validation error for invalid override unit price")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Return validation error for invalid override unit price")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task ReturnValidationErrorForInvalidOverrideUnitPrice()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Return validation error for invalid override unit price", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 231
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 232
    await testRunner.GivenAsync("override unit price is -100", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 233
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 234
    await testRunner.ThenAsync("validation error should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 235
    await testRunner.AndAsync("no invoice should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Return validation error for invalid override quantity")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Return validation error for invalid override quantity")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task ReturnValidationErrorForInvalidOverrideQuantity()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Return validation error for invalid override quantity", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 239
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 240
    await testRunner.GivenAsync("override quantity is -1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 241
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 242
    await testRunner.ThenAsync("validation error should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 243
    await testRunner.AndAsync("no invoice should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Return validation error for invalid meter consumption")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Return validation error for invalid meter consumption")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task ReturnValidationErrorForInvalidMeterConsumption()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Return validation error for invalid meter consumption", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 247
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 248
    await testRunner.GivenAsync("water service enabled with unit price 10000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Previous",
                            "Current"});
                table17.AddRow(new string[] {
                            "-----------",
                            "----------"});
                table17.AddRow(new string[] {
                            "100",
                            "90"});
#line 249
    await testRunner.AndAsync("meter reading for room \"101\":", ((string)(null)), table17, "And ");
#line hidden
#line 255
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 256
    await testRunner.ThenAsync("validation error should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 257
    await testRunner.AndAsync("no invoice should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Meter reset is handled correctly")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Meter reset is handled correctly")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task MeterResetIsHandledCorrectly()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Meter reset is handled correctly", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 260
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 261
      await testRunner.GivenAsync("previous meter reading is 1000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 262
      await testRunner.AndAsync("new meter is replaced with reading 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 263
      await testRunner.WhenAsync("I generate invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 264
      await testRunner.ThenAsync("system should create a new meter baseline or flag error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Duplicate meter readings should be ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Duplicate meter readings should be ignored")]
        [Xunit.TraitAttribute("Category", "Service")]
        public async System.Threading.Tasks.Task DuplicateMeterReadingsShouldBeIgnored()
        {
            string[] tagsOfScenario = new string[] {
                    "Service"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate meter readings should be ignored", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 267
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 268
      await testRunner.GivenAsync("multiple meter readings exist for same period", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 269
      await testRunner.WhenAsync("I generate invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 270
      await testRunner.ThenAsync("only latest valid reading should be used", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Generate invoice successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Generate invoice successfully")]
        [Xunit.TraitAttribute("Category", "Invoice")]
        public async System.Threading.Tasks.Task GenerateInvoiceSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "Invoice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate invoice successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 278
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 279
    await testRunner.GivenAsync("no invoice exists for room \"101\" in March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 280
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 281
    await testRunner.ThenAsync("an invoice should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 282
    await testRunner.AndAsync("invoice status should be \"Draft\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Skip invoice generation when invoice already exists")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Skip invoice generation when invoice already exists")]
        [Xunit.TraitAttribute("Category", "Invoice")]
        public async System.Threading.Tasks.Task SkipInvoiceGenerationWhenInvoiceAlreadyExists()
        {
            string[] tagsOfScenario = new string[] {
                    "Invoice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Skip invoice generation when invoice already exists", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 286
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 287
    await testRunner.GivenAsync("invoice already exists for room \"101\" in March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 288
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 289
    await testRunner.ThenAsync("invoice generation should be skipped", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 290
    await testRunner.AndAsync("only one invoice should exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invoice generation is idempotent")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Invoice generation is idempotent")]
        [Xunit.TraitAttribute("Category", "Invoice")]
        public async System.Threading.Tasks.Task InvoiceGenerationIsIdempotent()
        {
            string[] tagsOfScenario = new string[] {
                    "Invoice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invoice generation is idempotent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 294
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 295
    await testRunner.GivenAsync("no invoice exists for room \"101\" in March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 296
    await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 297
    await testRunner.AndAsync("I generate invoice for March 2026 again", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 298
    await testRunner.ThenAsync("only one invoice should exist", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate invoice with multiple services")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Calculate invoice with multiple services")]
        [Xunit.TraitAttribute("Category", "Invoice")]
        public async System.Threading.Tasks.Task CalculateInvoiceWithMultipleServices()
        {
            string[] tagsOfScenario = new string[] {
                    "Invoice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate invoice with multiple services", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 301
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 302
      await testRunner.GivenAsync("electricity service enabled with unit price 3000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 303
      await testRunner.AndAsync("water service enabled with unit price 10000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 304
      await testRunner.AndAsync("internet service enabled with unit price 100000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 305
      await testRunner.AndAsync("room \"101\" has 2 occupants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Service",
                            "Consumption"});
                table18.AddRow(new string[] {
                            "Electricity",
                            "100"});
                table18.AddRow(new string[] {
                            "Water",
                            "10"});
#line 306
      await testRunner.AndAsync("meter readings exist:", ((string)(null)), table18, "And ");
#line hidden
#line 310
      await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table19.AddRow(new string[] {
                            "TotalAmount",
                            "5310000"});
#line 311
      await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table19, "Then ");
#line hidden
#line 314
      await testRunner.AndAsync("invoice should include 3 service items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Skip missing meter services but still calculate others")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Skip missing meter services but still calculate others")]
        [Xunit.TraitAttribute("Category", "Invoice")]
        public async System.Threading.Tasks.Task SkipMissingMeterServicesButStillCalculateOthers()
        {
            string[] tagsOfScenario = new string[] {
                    "Invoice"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Skip missing meter services but still calculate others", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 317
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 318
      await testRunner.GivenAsync("electricity service enabled but missing meter reading", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 319
      await testRunner.AndAsync("water service enabled with valid meter reading", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 320
      await testRunner.WhenAsync("I generate invoice for March 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 321
      await testRunner.ThenAsync("electricity service should be skipped", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 322
      await testRunner.AndAsync("water service should be included", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 323
      await testRunner.AndAsync("invoice should still be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Send invoice changes status from Draft to Sent")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Send invoice changes status from Draft to Sent")]
        [Xunit.TraitAttribute("Category", "InvoiceStatus")]
        public async System.Threading.Tasks.Task SendInvoiceChangesStatusFromDraftToSent()
        {
            string[] tagsOfScenario = new string[] {
                    "InvoiceStatus"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send invoice changes status from Draft to Sent", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 326
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 327
      await testRunner.GivenAsync("an invoice exists in Draft status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 328
      await testRunner.WhenAsync("owner sends invoice to tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 329
      await testRunner.ThenAsync("invoice status should be \"Sent\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Partial payment changes invoice to Partially Paid")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Partial payment changes invoice to Partially Paid")]
        [Xunit.TraitAttribute("Category", "InvoiceStatus")]
        public async System.Threading.Tasks.Task PartialPaymentChangesInvoiceToPartiallyPaid()
        {
            string[] tagsOfScenario = new string[] {
                    "InvoiceStatus"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Partial payment changes invoice to Partially Paid", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 332
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 333
      await testRunner.GivenAsync("an invoice is in Sent status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 334
      await testRunner.WhenAsync("tenant pays part of the invoice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 335
      await testRunner.ThenAsync("invoice status should be \"PartiallyPaid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full payment completes invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Full payment completes invoice")]
        [Xunit.TraitAttribute("Category", "InvoiceStatus")]
        public async System.Threading.Tasks.Task FullPaymentCompletesInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "InvoiceStatus"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Full payment completes invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 338
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 339
      await testRunner.GivenAsync("an invoice is in Sent status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 340
      await testRunner.WhenAsync("tenant pays full amount", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 341
      await testRunner.ThenAsync("invoice status should be \"Paid\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Overdue is triggered after due date passes")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Overdue is triggered after due date passes")]
        [Xunit.TraitAttribute("Category", "InvoiceStatus")]
        public async System.Threading.Tasks.Task OverdueIsTriggeredAfterDueDatePasses()
        {
            string[] tagsOfScenario = new string[] {
                    "InvoiceStatus"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Overdue is triggered after due date passes", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 344
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 345
      await testRunner.GivenAsync("an invoice in Sent status with due date passed 24 hours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 346
      await testRunner.WhenAsync("system runs overdue check job", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 347
      await testRunner.ThenAsync("invoice status should be \"Overdue\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Multiple partial payments are accumulated correctly")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Multiple partial payments are accumulated correctly")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task MultiplePartialPaymentsAreAccumulatedCorrectly()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple partial payments are accumulated correctly", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 350
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 351
      await testRunner.GivenAsync("invoice total is 5,000,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 352
      await testRunner.WhenAsync("tenant pays 1,000,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 353
      await testRunner.AndAsync("tenant pays 2,000,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 354
      await testRunner.ThenAsync("total paid amount should be 3,000,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Overpayment is rejected or capped")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Overpayment is rejected or capped")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task OverpaymentIsRejectedOrCapped()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Overpayment is rejected or capped", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 357
      this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 358
        await testRunner.GivenAsync("invoice total is 5,000,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 359
        await testRunner.WhenAsync("tenant attempts to pay 6,000,000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 360
        await testRunner.ThenAsync("payment should be rejected or capped at invoice total", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Payment not allowed on Draft invoice")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Payment not allowed on Draft invoice")]
        [Xunit.TraitAttribute("Category", "Payment")]
        public async System.Threading.Tasks.Task PaymentNotAllowedOnDraftInvoice()
        {
            string[] tagsOfScenario = new string[] {
                    "Payment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Payment not allowed on Draft invoice", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 363
      this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 364
        await testRunner.GivenAsync("invoice is in Draft status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 365
        await testRunner.WhenAsync("tenant attempts to pay", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 366
        await testRunner.ThenAsync("payment should be rejected", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Apply penalty and discount")]
        [Xunit.TraitAttribute("FeatureTitle", "Monthly Invoice Calculation")]
        [Xunit.TraitAttribute("Description", "Apply penalty and discount")]
        [Xunit.TraitAttribute("Category", "Adjustment")]
        public async System.Threading.Tasks.Task ApplyPenaltyAndDiscount()
        {
            string[] tagsOfScenario = new string[] {
                    "Adjustment"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Apply penalty and discount", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 373
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 374
    await testRunner.WhenAsync("I generate invoice for March 2026 with penalty 500000 and discount 100000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table20.AddRow(new string[] {
                            "RoomAmount",
                            "5000000"});
                table20.AddRow(new string[] {
                            "PenaltyAmount",
                            "500000"});
                table20.AddRow(new string[] {
                            "DiscountAmount",
                            "100000"});
                table20.AddRow(new string[] {
                            "TotalAmount",
                            "5400000"});
#line 375
    await testRunner.ThenAsync("the invoice should contain:", ((string)(null)), table20, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await MonthlyInvoiceCalculationFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await MonthlyInvoiceCalculationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
