// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Acceptance.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Move_OutProcessFeature : object, Xunit.IClassFixture<Move_OutProcessFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "MoveOutProcess.feature"
#line hidden
        
        public Move_OutProcessFeature(Move_OutProcessFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Move-out Process", "  As a Building Owner\r\n  I want to correctly process tenant move-outs\r\n  So that " +
                    "deposit refunds are calculated fairly and all state transitions happen correctly" +
                    "", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a building owner for move-out tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("a building for move-out tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("a room \"201\" with deposit 10000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("a tenant for move-out tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("an active contract with deposit 10000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Full refund when no deductions")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Full refund when no deductions")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Deposit")]
        public async System.Threading.Tasks.Task FullRefundWhenNoDeductions()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Deposit"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Full refund when no deductions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("the deposit status should be \"Refunded\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
    await testRunner.AndAsync("the refund amount should be 10000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("a DEPOSIT_REFUND payment of 10000000 VND should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Partial refund when there are deductions")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Partial refund when there are deductions")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Deposit")]
        public async System.Threading.Tasks.Task PartialRefundWhenThereAreDeductions()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Deposit"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Partial refund when there are deductions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("deductions of 3000000 VND for damages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 28
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("the deposit status should be \"PartiallyRefunded\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("the refund amount should be 7000000 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("a DEPOSIT_REFUND payment of 7000000 VND should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deposit forfeited when deductions equal full deposit")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Deposit forfeited when deductions equal full deposit")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Deposit")]
        public async System.Threading.Tasks.Task DepositForfeitedWhenDeductionsEqualFullDeposit()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Deposit"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deposit forfeited when deductions equal full deposit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("deductions of 10000000 VND for damages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("the deposit status should be \"Forfeited\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.AndAsync("the refund amount should be 0 VND", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.AndAsync("an audit DEPOSIT_REFUND payment of 0 VND should be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Contract status changes to Terminated")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Contract status changes to Terminated")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Status")]
        public async System.Threading.Tasks.Task ContractStatusChangesToTerminated()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Status"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Contract status changes to Terminated", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 47
    await testRunner.GivenAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("the contract status should be \"Terminated\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
    await testRunner.AndAsync("the termination date should be \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Occupied room becomes available after move-out")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Occupied room becomes available after move-out")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Status")]
        public async System.Threading.Tasks.Task OccupiedRoomBecomesAvailableAfterMove_Out()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Status"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Occupied room becomes available after move-out", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.GivenAsync("the room is occupied by the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 55
    await testRunner.AndAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("the room status should be \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Room in maintenance stays in maintenance after move-out")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Room in maintenance stays in maintenance after move-out")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Status")]
        public async System.Threading.Tasks.Task RoomInMaintenanceStaysInMaintenanceAfterMove_Out()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Status"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Room in maintenance stays in maintenance after move-out", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 61
    await testRunner.GivenAsync("the room is in maintenance status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
    await testRunner.AndAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
    await testRunner.ThenAsync("the room status should be \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Move-out date is recorded for all active tenants")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Move-out date is recorded for all active tenants")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Tenants")]
        public async System.Threading.Tasks.Task Move_OutDateIsRecordedForAllActiveTenants()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Tenants"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Move-out date is recorded for all active tenants", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 72
    await testRunner.GivenAsync("the contract has 2 active occupants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 73
    await testRunner.AndAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
    await testRunner.ThenAsync("all active occupants should have move-out date \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Future unpaid invoices are voided on termination")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Future unpaid invoices are voided on termination")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Invoices")]
        public async System.Threading.Tasks.Task FutureUnpaidInvoicesAreVoidedOnTermination()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Invoices"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Future unpaid invoices are voided on termination", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 83
    await testRunner.GivenAsync("there is a Draft invoice for July 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 84
    await testRunner.AndAsync("there is a Sent invoice for August 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.AndAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 87
    await testRunner.ThenAsync("the July 2026 invoice should be Void", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
    await testRunner.AndAsync("the August 2026 invoice should be Void", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invoice for the termination month is not voided")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Invoice for the termination month is not voided")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Invoices")]
        public async System.Threading.Tasks.Task InvoiceForTheTerminationMonthIsNotVoided()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Invoices"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invoice for the termination month is not voided", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 91
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 92
    await testRunner.GivenAsync("there is a Draft invoice for June 2026", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 93
    await testRunner.AndAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 94
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 95
    await testRunner.ThenAsync("the June 2026 invoice should still be Draft", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Future invoice with existing payment is not voided")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Future invoice with existing payment is not voided")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Invoices")]
        public async System.Threading.Tasks.Task FutureInvoiceWithExistingPaymentIsNotVoided()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Invoices"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Future invoice with existing payment is not voided", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 98
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 99
    await testRunner.GivenAsync("there is a Sent invoice for July 2026 with a payment", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 100
    await testRunner.AndAsync("no deductions on move-out", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 101
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 102
    await testRunner.ThenAsync("the July 2026 invoice should still be Sent", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot terminate an already terminated contract")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Cannot terminate an already terminated contract")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotTerminateAnAlreadyTerminatedContract()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot terminate an already terminated contract", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 110
    await testRunner.GivenAsync("the contract is already terminated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 111
    await testRunner.WhenAsync("I try to terminate the contract on \"2026-07-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 112
    await testRunner.ThenAsync("the move-out should be rejected with conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deductions cannot be negative")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Deductions cannot be negative")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task DeductionsCannotBeNegative()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deductions cannot be negative", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 115
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 116
    await testRunner.GivenAsync("deductions of -500000 VND for damages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 117
    await testRunner.WhenAsync("I try to terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 118
    await testRunner.ThenAsync("the move-out should be rejected with validation error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deductions cannot exceed deposit amount")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Deductions cannot exceed deposit amount")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task DeductionsCannotExceedDepositAmount()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deductions cannot exceed deposit amount", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 122
    await testRunner.GivenAsync("deductions of 15000000 VND for damages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.WhenAsync("I try to terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.ThenAsync("the move-out should be rejected with validation error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Termination date cannot be before contract start date")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Termination date cannot be before contract start date")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task TerminationDateCannotBeBeforeContractStartDate()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Termination date cannot be before contract start date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 127
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 128
    await testRunner.WhenAsync("I try to terminate the contract on \"2025-12-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 129
    await testRunner.ThenAsync("the move-out should be rejected with validation error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Termination note is saved with deduction reason")]
        [Xunit.TraitAttribute("FeatureTitle", "Move-out Process")]
        [Xunit.TraitAttribute("Description", "Termination note is saved with deduction reason")]
        [Xunit.TraitAttribute("Category", "MoveOut")]
        [Xunit.TraitAttribute("Category", "Note")]
        public async System.Threading.Tasks.Task TerminationNoteIsSavedWithDeductionReason()
        {
            string[] tagsOfScenario = new string[] {
                    "MoveOut",
                    "Note"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Termination note is saved with deduction reason", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 136
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 137
    await testRunner.GivenAsync("deductions of 2000000 VND for damages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 138
    await testRunner.AndAsync("a note \"Hư hỏng tường và cửa sổ\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.WhenAsync("I terminate the contract on \"2026-06-30\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 140
    await testRunner.ThenAsync("the termination note \"Hư hỏng tường và cửa sổ\" should be saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await Move_OutProcessFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await Move_OutProcessFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
