// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Acceptance.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PostMove_OutMaintenanceProcessFeature : object, Xunit.IClassFixture<PostMove_OutMaintenanceProcessFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PostMoveOutMaintenance.feature"
#line hidden
        
        public PostMove_OutMaintenanceProcessFeature(PostMove_OutMaintenanceProcessFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Post Move-out Maintenance Process", "  As a Building Owner or Staff\r\n  I want to set a room to Maintenance after a ten" +
                    "ant moves out\r\n  So that the room is blocked from new bookings until repairs are" +
                    " complete", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a building owner for maintenance tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("a building for maintenance tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("a room \"301\" in Available status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner sets Available room to Maintenance after move-out")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Owner sets Available room to Maintenance after move-out")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "HappyPath")]
        public async System.Threading.Tasks.Task OwnerSetsAvailableRoomToMaintenanceAfterMove_Out()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "HappyPath"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Owner sets Available room to Maintenance after move-out", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 17
    await testRunner.WhenAsync("I change the room status to \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 18
    await testRunner.ThenAsync("the room status in the database should be \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Owner sets Maintenance room back to Available after repairs")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Owner sets Maintenance room back to Available after repairs")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "HappyPath")]
        public async System.Threading.Tasks.Task OwnerSetsMaintenanceRoomBackToAvailableAfterRepairs()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "HappyPath"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Owner sets Maintenance room back to Available after repairs", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
    await testRunner.GivenAsync("the room is in Maintenance status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 23
    await testRunner.WhenAsync("I change the room status to \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("the room status in the database should be \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Status change is case-insensitive")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Status change is case-insensitive")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "HappyPath")]
        public async System.Threading.Tasks.Task StatusChangeIsCase_Insensitive()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "HappyPath"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Status change is case-insensitive", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.WhenAsync("I change the room status to \"maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("the room status in the database should be \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Round-trip Available to Maintenance and back")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Round-trip Available to Maintenance and back")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "HappyPath")]
        public async System.Threading.Tasks.Task Round_TripAvailableToMaintenanceAndBack()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "HappyPath"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Round-trip Available to Maintenance and back", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
    await testRunner.WhenAsync("I change the room status to \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("the room status in the database should be \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.WhenAsync("I change the room status to \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("the room status in the database should be \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot manually set room to Occupied")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Cannot manually set room to Occupied")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotManuallySetRoomToOccupied()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot manually set room to Occupied", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
    await testRunner.WhenAsync("I try to change the room status to \"Occupied\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.ThenAsync("the status change should be rejected with a bad request error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot manually set room to Booked")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Cannot manually set room to Booked")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotManuallySetRoomToBooked()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot manually set room to Booked", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.WhenAsync("I try to change the room status to \"Booked\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("the status change should be rejected with a bad request error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid status string is rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Invalid status string is rejected")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task InvalidStatusStringIsRejected()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid status string is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 54
    await testRunner.WhenAsync("I try to change the room status to \"Broken\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 55
    await testRunner.ThenAsync("the status change should be rejected with a bad request error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot change status of an Occupied room")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Cannot change status of an Occupied room")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotChangeStatusOfAnOccupiedRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot change status of an Occupied room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync("the room is in Occupied status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("I try to change the room status to \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("the status change should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot change status of a Booked room")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Cannot change status of a Booked room")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotChangeStatusOfABookedRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot change status of a Booked room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 68
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 69
    await testRunner.GivenAsync("the room is in Booked status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 70
    await testRunner.WhenAsync("I try to change the room status to \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("the status change should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot set Maintenance room to Maintenance again")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Cannot set Maintenance room to Maintenance again")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotSetMaintenanceRoomToMaintenanceAgain()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot set Maintenance room to Maintenance again", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 79
    await testRunner.GivenAsync("the room is in Maintenance status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 80
    await testRunner.WhenAsync("I try to change the room status to \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 81
    await testRunner.ThenAsync("the status change should be rejected with a bad request error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot set Available room to Available again")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Cannot set Available room to Available again")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task CannotSetAvailableRoomToAvailableAgain()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot set Available room to Available again", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 85
    await testRunner.WhenAsync("I try to change the room status to \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.ThenAsync("the status change should be rejected with a bad request error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Failed transition does not change persisted status")]
        [Xunit.TraitAttribute("FeatureTitle", "Post Move-out Maintenance Process")]
        [Xunit.TraitAttribute("Description", "Failed transition does not change persisted status")]
        [Xunit.TraitAttribute("Category", "Maintenance")]
        [Xunit.TraitAttribute("Category", "Validation")]
        public async System.Threading.Tasks.Task FailedTransitionDoesNotChangePersistedStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "Maintenance",
                    "Validation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed transition does not change persisted status", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 93
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 94
    await testRunner.GivenAsync("the room is in Occupied status", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.WhenAsync("I try to change the room status to \"Maintenance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.ThenAsync("the room status in the database should be \"Occupied\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PostMove_OutMaintenanceProcessFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PostMove_OutMaintenanceProcessFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
