// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Tests.Acceptance.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RentalProcessFeature : object, Xunit.IClassFixture<RentalProcessFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "RentalProcess.feature"
#line hidden
        
        public RentalProcessFeature(RentalProcessFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Rental Process", "  As a Building Owner\r\n  I want to manage the full tenant rental lifecycle\r\n  So " +
                    "that room availability, deposits, and contracts stay in sync at every step", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            TechTalk.SpecFlow.xUnit.SpecFlowPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a building owner for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("a building for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("an available room \"101\" priced at 5000000 VND for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("a tenant for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Direct contract changes room to Occupied")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Direct contract changes room to Occupied")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DirectContract")]
        public async System.Threading.Tasks.Task DirectContractChangesRoomToOccupied()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DirectContract"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Direct contract changes room to Occupied", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.WhenAsync("I create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("the contract status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("the room status should be \"Occupied\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Direct contract creates DEPOSIT_IN payment")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Direct contract creates DEPOSIT_IN payment")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DirectContract")]
        public async System.Threading.Tasks.Task DirectContractCreatesDEPOSIT_INPayment()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DirectContract"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Direct contract creates DEPOSIT_IN payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.WhenAsync("I create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("a DEPOSIT_IN payment of 10000000 should be recorded for the contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Direct contract auto-creates main tenant record")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Direct contract auto-creates main tenant record")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DirectContract")]
        public async System.Threading.Tasks.Task DirectContractAuto_CreatesMainTenantRecord()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DirectContract"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Direct contract auto-creates main tenant record", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.WhenAsync("I create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the contract should have 1 tenant with IsMainTenant true", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Direct contract sends notification to tenant")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Direct contract sends notification to tenant")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DirectContract")]
        public async System.Threading.Tasks.Task DirectContractSendsNotificationToTenant()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DirectContract"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Direct contract sends notification to tenant", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.WhenAsync("I create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("a contract notification should be created for the tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot create direct contract for non-Available room")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot create direct contract for non-Available room")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DirectContract")]
        public async System.Threading.Tasks.Task CannotCreateDirectContractForNon_AvailableRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DirectContract"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot create direct contract for non-Available room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 40
    await testRunner.GivenAsync("the room is in Maintenance status for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 41
    await testRunner.WhenAsync("I try to create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot create zero-deposit contract on Occupied room (UQ-01)")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot create zero-deposit contract on Occupied room (UQ-01)")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DirectContract")]
        public async System.Threading.Tasks.Task CannotCreateZero_DepositContractOnOccupiedRoomUQ_01()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DirectContract"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot create zero-deposit contract on Occupied room (UQ-01)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.WhenAsync("I create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.AndAsync("I try to create a second direct contract on the same room", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Creating reservation changes room to Booked")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Creating reservation changes room to Booked")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task CreatingReservationChangesRoomToBooked()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Creating reservation changes room to Booked", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 56
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 57
    await testRunner.WhenAsync("I create a reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("the reservation status should be \"Pending\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("the room status should be \"Booked\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Confirming reservation changes status to Confirmed")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Confirming reservation changes status to Confirmed")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task ConfirmingReservationChangesStatusToConfirmed()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirming reservation changes status to Confirmed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("I confirm the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("the reservation status should be \"Confirmed\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 66
    await testRunner.AndAsync("the room status should be \"Booked\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Contract from confirmed reservation converts reservation and occupies room")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Contract from confirmed reservation converts reservation and occupies room")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task ContractFromConfirmedReservationConvertsReservationAndOccupiesRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Contract from confirmed reservation converts reservation and occupies room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 69
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 70
    await testRunner.GivenAsync("a confirmed reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 71
    await testRunner.WhenAsync("I create a contract from the reservation with monthly rent 5000000 and deposit 50" +
                        "00000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 72
    await testRunner.ThenAsync("the contract status should be \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 73
    await testRunner.AndAsync("the room status should be \"Occupied\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.AndAsync("the reservation status should be \"Converted\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Reservation deposit carries over as DEPOSIT_IN payment")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Reservation deposit carries over as DEPOSIT_IN payment")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task ReservationDepositCarriesOverAsDEPOSIT_INPayment()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reservation deposit carries over as DEPOSIT_IN payment", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 78
    await testRunner.GivenAsync("a confirmed reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 79
    await testRunner.WhenAsync("I create a contract from the reservation with monthly rent 5000000 and deposit 50" +
                        "00000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 80
    await testRunner.ThenAsync("a DEPOSIT_IN payment of 5000000 should be recorded for the contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Additional deposit created when contract deposit exceeds reservation deposit")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Additional deposit created when contract deposit exceeds reservation deposit")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task AdditionalDepositCreatedWhenContractDepositExceedsReservationDeposit()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Additional deposit created when contract deposit exceeds reservation deposit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 84
    await testRunner.GivenAsync("a confirmed reservation with deposit 3000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 85
    await testRunner.WhenAsync("I create a contract from the reservation with monthly rent 5000000 and deposit 80" +
                        "00000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 86
    await testRunner.ThenAsync("a DEPOSIT_IN payment of 3000000 should be recorded for the contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.AndAsync("a DEPOSIT_IN payment of 5000000 should be recorded for the contract", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot create contract from Pending reservation")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot create contract from Pending reservation")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task CannotCreateContractFromPendingReservation()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot create contract from Pending reservation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 90
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 91
    await testRunner.GivenAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 92
    await testRunner.WhenAsync("I try to create a contract from the reservation with monthly rent 5000000 and dep" +
                        "osit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot create contract if contract deposit is less than reservation deposit")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot create contract if contract deposit is less than reservation deposit")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Reservation")]
        public async System.Threading.Tasks.Task CannotCreateContractIfContractDepositIsLessThanReservationDeposit()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Reservation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot create contract if contract deposit is less than reservation deposit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 96
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 97
    await testRunner.GivenAsync("a confirmed reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 98
    await testRunner.WhenAsync("I try to create a contract from the reservation with monthly rent 5000000 and dep" +
                        "osit 3000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("the rental action should be rejected with a bad request error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelling a Pending reservation frees the room")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cancelling a Pending reservation frees the room")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Cancellation")]
        public async System.Threading.Tasks.Task CancellingAPendingReservationFreesTheRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Cancellation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancelling a Pending reservation frees the room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 108
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 109
    await testRunner.GivenAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 110
    await testRunner.WhenAsync("I cancel the reservation with refund 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 111
    await testRunner.ThenAsync("the reservation status should be \"Cancelled\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
    await testRunner.AndAsync("the room status should be \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelling a Pending reservation does not create deposit payments")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cancelling a Pending reservation does not create deposit payments")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Cancellation")]
        public async System.Threading.Tasks.Task CancellingAPendingReservationDoesNotCreateDepositPayments()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Cancellation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancelling a Pending reservation does not create deposit payments", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 115
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 116
    await testRunner.GivenAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 117
    await testRunner.WhenAsync("I cancel the reservation with refund 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 118
    await testRunner.ThenAsync("no deposit payments should exist for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelling a Confirmed reservation with full refund creates two payments")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cancelling a Confirmed reservation with full refund creates two payments")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Cancellation")]
        public async System.Threading.Tasks.Task CancellingAConfirmedReservationWithFullRefundCreatesTwoPayments()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Cancellation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancelling a Confirmed reservation with full refund creates two payments", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 122
    await testRunner.GivenAsync("a confirmed reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 123
    await testRunner.WhenAsync("I cancel the reservation with refund 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 124
    await testRunner.ThenAsync("a DEPOSIT_IN payment of 5000000 should be recorded for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
    await testRunner.AndAsync("a DEPOSIT_REFUND payment of 5000000 should be recorded for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 126
    await testRunner.AndAsync("the room status should be \"Available\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelling a Confirmed reservation with zero refund forfeits deposit")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cancelling a Confirmed reservation with zero refund forfeits deposit")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Cancellation")]
        public async System.Threading.Tasks.Task CancellingAConfirmedReservationWithZeroRefundForfeitsDeposit()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Cancellation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancelling a Confirmed reservation with zero refund forfeits deposit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 129
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 130
    await testRunner.GivenAsync("a confirmed reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 131
    await testRunner.WhenAsync("I cancel the reservation with refund 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 132
    await testRunner.ThenAsync("a DEPOSIT_IN payment of 5000000 should be recorded for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 133
    await testRunner.AndAsync("no DEPOSIT_REFUND payment should exist for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 134
    await testRunner.AndAsync("the reservation refund amount should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cancelling a Confirmed reservation with partial refund")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cancelling a Confirmed reservation with partial refund")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Cancellation")]
        public async System.Threading.Tasks.Task CancellingAConfirmedReservationWithPartialRefund()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Cancellation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancelling a Confirmed reservation with partial refund", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 137
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 138
    await testRunner.GivenAsync("a confirmed reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 139
    await testRunner.WhenAsync("I cancel the reservation with refund 2000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 140
    await testRunner.ThenAsync("a DEPOSIT_IN payment of 5000000 should be recorded for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 141
    await testRunner.AndAsync("a DEPOSIT_REFUND payment of 2000000 should be recorded for the reservation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot cancel an already-Cancelled reservation")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot cancel an already-Cancelled reservation")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "Cancellation")]
        public async System.Threading.Tasks.Task CannotCancelAnAlready_CancelledReservation()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "Cancellation"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot cancel an already-Cancelled reservation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 144
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 145
    await testRunner.GivenAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 146
    await testRunner.AndAsync("the reservation has been cancelled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 147
    await testRunner.WhenAsync("I try to cancel the reservation again with refund 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 148
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot reserve an already-Booked room")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot reserve an already-Booked room")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DoubleBooking")]
        public async System.Threading.Tasks.Task CannotReserveAnAlready_BookedRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DoubleBooking"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot reserve an already-Booked room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 155
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 156
    await testRunner.GivenAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 157
    await testRunner.GivenAsync("a second tenant for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 158
    await testRunner.WhenAsync("I try to create a reservation for the second tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 159
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cannot reserve an Occupied room")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Cannot reserve an Occupied room")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DoubleBooking")]
        public async System.Threading.Tasks.Task CannotReserveAnOccupiedRoom()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DoubleBooking"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cannot reserve an Occupied room", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 162
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 163
    await testRunner.GivenAsync("a second tenant for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 164
    await testRunner.WhenAsync("I create a direct contract with monthly rent 5000000 and deposit 10000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 165
    await testRunner.AndAsync("I try to create a reservation for the second tenant", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 166
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tenant cannot have two active reservations simultaneously")]
        [Xunit.TraitAttribute("FeatureTitle", "Rental Process")]
        [Xunit.TraitAttribute("Description", "Tenant cannot have two active reservations simultaneously")]
        [Xunit.TraitAttribute("Category", "Rental")]
        [Xunit.TraitAttribute("Category", "DoubleBooking")]
        public async System.Threading.Tasks.Task TenantCannotHaveTwoActiveReservationsSimultaneously()
        {
            string[] tagsOfScenario = new string[] {
                    "Rental",
                    "DoubleBooking"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tenant cannot have two active reservations simultaneously", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 169
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 170
    await testRunner.GivenAsync("a second available room \"102\" for rental tests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 171
    await testRunner.AndAsync("a pending reservation with deposit 5000000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 172
    await testRunner.WhenAsync("I try to create a second reservation on room \"102\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 173
    await testRunner.ThenAsync("the rental action should be rejected with a conflict error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await RentalProcessFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await RentalProcessFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
